[package]
name = "eagle-eye-server"
version = "0.1.0"
edition = "2024"

[dependencies]
eagle-eye-broadcaster = { path = "../eagle-eye-broadcaster" }
eagle-eye-proto = { path = "../eagle-eye-proto" }
eagle-eye-jobs = { path = "../eagle-eye-jobs"}
