[package]
name = "eagle-eye-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
# tokio = { version = "1", features = ["rt", "net", "io-util"]}
aes = { workspace = true }
cbc = { workspace = true }
ctr = { workspace = true }
rand = { workspace = true }

