[package]
name = "ee-task"
version = "0.1.0"
edition = "2024"

[dependencies]
ee-http = { path = "../ee-http" }
ee-stream = { path = "../ee-stream" }
serde = { workspace = true }
serde_json = { workspace = true }
